openapi: 3.0.0
info:
  version: 0.0.1
  title: API
paths:
  /brute-force/execute:
    post:
      summary: stat algorithm executing
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                starsCount:
                  type: number
      responses:
        '200':
          description: maybe wait amount of time
  /initial-graph/post-file:
    post:
      summary: get initial graph
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                size:
                  type: number
                  example: 1
                nodeWeights:
                  type: array
                  items:
                    type: number
                    example: 1
                matrix:
                  type: array
                  items:
                    type: array
                    items:
                      type: number
                  example:
                    -
                      - 1
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Graph'
          description: successful operation
  /brute-force/solution/{number}:
    get:
      summary: get solution with certain number
      parameters:
        - in: path
          name: number
          required: true
          schema:
            type: number
      responses:
        '200':
          description: return graphical representation of solution with certain number
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Graph'
        '404':
          description: process not found
  /brute-force/solution/end:
    get:
      summary: get end solution
      responses:
        '200':
          description: return graphical representation of solution with certain number
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Graph'
        '404':
          description: did not find
components:
  schemas:
    Graph:
      type: object
      properties:
        nodes:
          type: array
          items:
            $ref: '#/components/schemas/node'
        edges:
          type: array
          items:
            $ref: '#/components/schemas/edge'
    node:
      type: object
      properties:
        data:
          type: object
          properties:
            id:
              type: number
              example: 0
            name:
              type: string
              example: "Node name"
            color:
              type: string
              example: "#ff00ff"
    edge:
      type: object
      properties:
        data:
          type: object
          properties:
            source:
              type: string
              example: '0'
            target:
              type: string
              example: '1'
            color:
              type: string
              example: '#ff0ff0'